//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditEntries
    {
        public int ID { get; set; }
        public string ActionType { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public string TableName { get; set; }
        public string PrimaryColumn { get; set; }
        public string PrimaryValue { get; set; }
        public string ChangeColumn { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    }
}
