//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.ClientProducts = new HashSet<ClientProducts>();
            this.Projects = new HashSet<Projects>();
            this.ClientStaff = new HashSet<ClientStaff>();
        }
    
        public int ID { get; set; }
        public int EntityID { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> AccountManagerID { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ClientProducts> ClientProducts { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Entities Entities { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual ICollection<ClientStaff> ClientStaff { get; set; }
    }
}
