//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientStaff
    {
        public ClientStaff()
        {
            this.ClientTeams = new HashSet<ClientTeams>();
        }
    
        public int ID { get; set; }
        public int ClientID { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string JobTitle { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
        public string FullName { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<ClientTeams> ClientTeams { get; set; }
    }
}
