//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTeamRoles
    {
        public ClientTeamRoles()
        {
            this.ClientTeams = new HashSet<ClientTeams>();
        }
    
        public string RoleCode { get; set; }
        public string RoleDescription { get; set; }
    
        public virtual ICollection<ClientTeams> ClientTeams { get; set; }
    }
}
