//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entities
    {
        public Entities()
        {
            this.Clients = new HashSet<Clients>();
            this.Projects = new HashSet<Projects>();
            this.Staff = new HashSet<Staff>();
            this.StaffEntities = new HashSet<StaffEntities>();
        }
    
        public int ID { get; set; }
        public string EntityName { get; set; }
        public string EntityDescription { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual ICollection<Staff> Staff { get; set; }
        public virtual ICollection<StaffEntities> StaffEntities { get; set; }
    }
}
