//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ClientProducts = new HashSet<ClientProducts>();
            this.ProjectProducts = new HashSet<ProjectProducts>();
        }
    
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> LatestVersion { get; set; }
        public string ProductDescription { get; set; }
    
        public virtual ICollection<ClientProducts> ClientProducts { get; set; }
        public virtual ICollection<ProjectProducts> ProjectProducts { get; set; }
    }
}
