//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStages
    {
        public ProjectStages()
        {
            this.Projects = new HashSet<Projects>();
            this.StageHistory = new HashSet<StageHistory>();
            this.SuggestedActions = new HashSet<SuggestedActions>();
        }
    
        public int ID { get; set; }
        public int StageNumber { get; set; }
        public string StageName { get; set; }
        public string StageDescription { get; set; }
        public string ProjectStatus { get; set; }
    
        public virtual ICollection<Projects> Projects { get; set; }
        public virtual ICollection<StageHistory> StageHistory { get; set; }
        public virtual ICollection<SuggestedActions> SuggestedActions { get; set; }
    }
}
