//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStages
    {
        public ProjectStages()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public int StageCode { get; set; }
        public string StageName { get; set; }
        public string StageDescription { get; set; }
        public string ProjectStatus { get; set; }
    
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
