//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRoles
    {
        public ProjectRoles()
        {
            this.ProjectTeams = new HashSet<ProjectTeams>();
        }
    
        public string RoleCode { get; set; }
        public string RoleDescription { get; set; }
    
        public virtual ICollection<ProjectTeams> ProjectTeams { get; set; }
    }
}
