//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProducts
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> OldVersion { get; set; }
        public decimal NewVersion { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
