//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public Projects()
        {
            this.ClientTeams = new HashSet<ClientTeams>();
            this.ProjectProducts = new HashSet<ProjectProducts>();
            this.ProjectTeams = new HashSet<ProjectTeams>();
            this.Staff = new HashSet<Staff>();
        }
    
        public int ID { get; set; }
        public int EntityID { get; set; }
        public string ProjectCode { get; set; }
        public string TypeCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public int StageCode { get; set; }
        public string ProjectSummary { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<ClientTeams> ClientTeams { get; set; }
        public virtual Entities Entities { get; set; }
        public virtual ICollection<ProjectProducts> ProjectProducts { get; set; }
        public virtual ProjectStages ProjectStages { get; set; }
        public virtual ProjectTypes ProjectTypes { get; set; }
        public virtual ICollection<ProjectTeams> ProjectTeams { get; set; }
        public virtual ICollection<Staff> Staff { get; set; }
    }
}
