//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTeams
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int StaffID { get; set; }
        public string ProjectRoleCode { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual ProjectRoles ProjectRoles { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
