//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffEntities
    {
        public int ID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> EntityID { get; set; }
    
        public virtual Entities Entities { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
