//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuggestedActions
    {
        public int ID { get; set; }
        public string ShortDescription { get; set; }
        public string InternalRole { get; set; }
        public string ClientRole { get; set; }
        public string Notes { get; set; }
        public Nullable<int> StageID { get; set; }
        public Nullable<decimal> TargetDuration { get; set; }
        public Nullable<bool> S_NS { get; set; }
        public Nullable<bool> S_AS { get; set; }
        public Nullable<bool> S_RB { get; set; }
        public Nullable<bool> S_UG { get; set; }
        public Nullable<bool> S_UR { get; set; }
        public Nullable<bool> S_RS { get; set; }
        public Nullable<bool> S_AF { get; set; }
        public Nullable<bool> S_TO { get; set; }
        public Nullable<bool> S_IP { get; set; }
    
        public virtual ProjectStages ProjectStages { get; set; }
    }
}
