//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePermissions
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public string RoleCode { get; set; }
        public Nullable<bool> ViewTable { get; set; }
        public Nullable<bool> UpdateRows { get; set; }
        public Nullable<bool> InsertRows { get; set; }
        public Nullable<bool> ChangeStatus { get; set; }
    
        public virtual StaffRoles StaffRoles { get; set; }
    }
}
