//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_ClientsWithProducts
    {
        public string EntityName { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> ProductVersion { get; set; }
        public Nullable<decimal> LatestVersion { get; set; }
        public string ProductDescription { get; set; }
    }
}
