//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_ClientsWithAccountManagers
    {
        public string EntityName { get; set; }
        public int ID { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public bool Active { get; set; }
        public string AccountManagerName { get; set; }
    }
}
