//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_ClientTeams
    {
        public string EntityName { get; set; }
        public string ClientName { get; set; }
        public string ProjectName { get; set; }
        public string StaffName { get; set; }
        public string JobTitle { get; set; }
        public string RoleDescription { get; set; }
    }
}
