//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTile
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_OpenProjectProducts
    {
        public string ProjectCode { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public string TypeName { get; set; }
        public string ProjectName { get; set; }
        public string StageName { get; set; }
        public string ProjectStatus { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> OldVersion { get; set; }
        public decimal NewVersion { get; set; }
        public decimal ClientVersion { get; set; }
    }
}
